### ISSUE TITLE
AstraDB Beta

### ISSUE THREAD

**Issue by scottlepp** [grafana/astradb-datasource#5]
- [x] Setup repo from template
- [x] Remove template references
- [x] Setup CI
- [x] Add Health Check
- [x] Add ConfigEditor Component
- [x] Implement backend Query
- [x] Add QueryEditor Component ( wrap experimental SqlEditor )
- [x] #8
- [x] #9
- [x] #7
- [x] #11
- [x] Update ReadMe/Docs
- [x] #10
- [x] #13 
- [x] #12 
- [x] Add plugin stub for deployment
- [x] Publish/Deploy
- [x] Setup e2e
- [x] #28
